version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_CICDGitmv0us2caProject
  gitServerName: SIQAGitHubTest
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: DADA_RefDocFlatfileTests
  gitServerName: SIQAGitHubTest
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
